package dataservice.informationchangedataservice._Driver;

import dataservice.informationchangedataservice.ConstantManageDataService;
import dataservice.informationchangedataservice.PeopleAgencyDataService;
import dataservice.informationchangedataservice._Stub.ConstantManageDataService_Stub;
import dataservice.informationchangedataservice._Stub.PeopleAgencyDataService_Stub;

public class informationchangedataservice_Driver {
	public static void main(String []args){
	ConstantManageDataService constantManageDataService=new ConstantManageDataService_Stub();
	ConstantManageDataService_Driver constantManageDataService_Driver=new ConstantManageDataService_Driver();
	constantManageDataService_Driver.drive(constantManageDataService);
	PeopleAgencyDataService peopleAgencyDataService=new PeopleAgencyDataService_Stub();
	PeopleAgencyDataService_Driver peopleAgencyDataService_Driver=new PeopleAgencyDataService_Driver();
	peopleAgencyDataService_Driver.drive(peopleAgencyDataService);
	}
}
